### ISSUE TITLE
Scheduler Related Issues (Mostly)

### ISSUE THREAD

**Issue by littlecube8152** [NTU-SP/SP2024_HW3_release#1]
Hello, I have several questions regarding some details of the implementation.

First, about some more important questions regarding the expected behaviour:
 - Does the idle thread print the message and yield every time it is scheduled? From the specification, if we simply return from the function, then it should return back to the `scheduler()` and every subsequent `longjmp()` to thread 0 (idle) will arrive at a corrupted stack. I am not sure if I implemented it correctly, but it shows `** stack smashing detected ***`. 
 - The specification stated that in `main.c`, `void start_threading()` sets up the alarm, and then calls the scheduler. However, the alarm is nowhere to be found in the source code. There were also few descriptions about how it should be done. Am I missing something important here, or there is just some piece of missing code?
 
 Secondly, about some minor questions about some tiny detail of implementation:
  - Are we allowed to handle part of the `thread_sleep(sec)` mechanism in the scheduler? Since there is still a way (pass some info along `longjmp()`) to do it, which is kind of against the specification, hence I am asking permission to write such implementation.
  
Finally, thank you for reviewing this issue.

**Comment by seantsao00** [comment]
Hello,

Thank you for your questions. Below are the clarifications and responses to your concerns:

**Idle Thread**
You are correct that the description for the idle thread was incomplete. We have addressed this issue in the 12/1 announcement. Please refer to the updated specification for details on how the idle thread should behave. Specifically, it should print the message and yield every time it is scheduled.

**Alarm**
The omission of alarm setup details was intentional, as we initially wanted students to explore the implementation independently. However, we recognized this caused confusion and decided to add clearer instructions in the 12/1 clarification. Please check the updated specification for guidance on alarm handling.

**Handling thread_sleep(sec) in the Scheduler**
You are welcome to implement your proposed approach, as long as it behaves identically to the specification. If your implementation achieves the same result as described, it is considered acceptable.

Thank you for bringing up these points, and we hope this clarifies your concerns. Let us know if you have further questions!
